---
- name: Install WP-CLI
  get_url: url={{ wp_cli_url }} dest={{ wp_cli_bin }} mode=0755

- name: Download WordPress
  command: wp core download --path={{ wp_root }} --locale={{ wp_lang }} --version={{ wp_version }} --allow-root creates={{ wp_root }}

